{% set name = "osmnx" %}
{% set version = "0.5.2" %}
{% set sha256 = "2aadb7f6d4ff7890d5b507bc4a0409b03372eb6da5b17fbf344c7f8842bf280e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests
    - numpy
    - pandas >=0.19
    - geopandas >=0.2.1
    - networkx
    - matplotlib >=2.0
    - shapely
    - descartes
    - geopy
    - rtree >=0.8.3
    - folium

test:
  imports:
    - osmnx

about:
  home: https://github.com/gboeing/osmnx
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Retrieve, construct, analyze, and visualize street networks from OpenStreetMap'
  description: |
    OSMnx is a Python 2 and 3 package that lets you download spatial geometries and
    construct, project, visualize, and analyze street networks from OpenStreetMap's
    APIs. You can download and construct walkable, drivable, or bikable urban networks
    with a single line of Python code, and then easily analyze and visualize them.
  doc_url: https://osmnx.readthedocs.io/en/stable/
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - ocefpaf
    - gboeing
