{% set name = "osmnx" %}
{% set version = "0.11.1" %}
{% set sha256 = "7bb64dc7cddb3af04ff87cda6240350e3d713977f0adc8ad03527e97792eb1ac" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - pip
    - python
  run:
    - descartes
    - folium
    - geopandas
    - geopy
    - matplotlib
    - networkx
    - numpy
    - pandas
    - python
    - requests
    - rtree
    - scipy
    - scikit-learn
    - shapely

test:
  imports:
    - osmnx

about:
  home: https://github.com/gboeing/osmnx
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Python for street networks. Retrieve, model, analyze, and visualize street networks and other spatial data from OpenStreetMap.'
  description: |
    OSMnx is a Python package that lets you download spatial geometries and
    model, project, visualize, and analyze street networks from OpenStreetMap's
    APIs. You can download and model walkable, drivable, or bikable urban networks
    with a single line of Python code, and then easily analyze and visualize them.
  doc_url: https://osmnx.readthedocs.io/
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - ocefpaf
    - gboeing
