{% set name = "osmnx" %}
{% set version = "1.1.2" %}
{% set sha256 = "e035523a0e2011425800dca0fdbb4dc41b55f6286960936e3dcf94e539c757e5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - folium
    - gdal
    - geopandas
    - matplotlib-base
    - networkx
    - numpy
    - pandas
    - pyproj
    - python >=3.7
    - rasterio
    - requests
    - rtree
    - scipy
    - scikit-learn
    - shapely

test:
  imports:
    - osmnx

about:
  home: https://github.com/gboeing/osmnx
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python for street networks. Retrieve, model, analyze, and visualize street networks and other spatial data from OpenStreetMap.
  description: OSMnx is a Python package that lets you download spatial geometries and model, project, visualize, and analyze real-world street networks from OpenStreetMap's APIs. Users can download and model walkable, drivable, or bikeable urban networks with a single line of Python code, and then easily analyze and visualize them. You can just as easily download and work with amenities/points of interest, building footprints, elevation data, street bearings/orientations, speed/travel time, and network routing.
  doc_url: https://osmnx.readthedocs.io/
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - ocefpaf
    - gboeing
