{% set name = "osmnx" %}
{% set version = "1.0.1" %}
{% set sha256 = "e44082ca5df063758e11afe0e0d1064d49266c66973039651618ec8cf8b009d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - descartes
    - folium
    - geopandas
    - matplotlib-base
    - networkx
    - numpy
    - pandas
    - pyproj
    - python
    - requests
    - rtree
    - scipy
    - scikit-learn
    - shapely

test:
  imports:
    - osmnx

about:
  home: https://github.com/gboeing/osmnx
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python for street networks. Retrieve, model, analyze, and visualize street networks and other spatial data from OpenStreetMap.
  description: OSMnx is a Python package that lets you download spatial geometries and model, project, visualize, and analyze real-world street networks from OpenStreetMap's APIs. Users can download and model walkable, drivable, or bikeable urban networks with a single line of Python code, and then easily analyze and visualize them. You can just as easily download and work with amenities/points of interest, building footprints, elevation data, street bearings/orientations, speed/travel time, and network routing.
  doc_url: https://osmnx.readthedocs.io/
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - ocefpaf
    - gboeing
