{% set name = "osmnx" %}
{% set version = "0.8.1" %}
{% set sha256 = "6f7e0caf2a32523bf825a7274abc62d958431b08408ec5b64a5ad43c004383a5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - numpy
    - pandas
    - geopandas
    - networkx >=2.1
    - matplotlib
    - shapely
    - descartes
    - geopy
    - rtree
    - folium

test:
  imports:
    - osmnx

about:
  home: https://github.com/gboeing/osmnx
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Retrieve, construct, analyze, and visualize street networks from OpenStreetMap'
  description: |
    OSMnx is a Python package that lets you download spatial geometries and
    construct, project, visualize, and analyze street networks from OpenStreetMap's
    APIs. You can download and construct walkable, drivable, or bikable urban networks
    with a single line of Python code, and then easily analyze and visualize them.
  doc_url: https://osmnx.readthedocs.io
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - ocefpaf
    - gboeing
