{% set name = "osmnx" %}
{% set version = "1.9.3" %}
{% set sha256 = "48775ffb28d25bf95d12d9fcb8fd6872d082891724077b5f063d6d02ae816000" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gboeing/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<38 or s390x]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - hatchling
    - pip
    - python
  run:
    - geopandas >=0.12
    - networkx >=2.5
    - numpy >=1.20
    - pandas >=1.1
    - python
    - requests >=2.27
    - shapely >=2.0
  run_constrained:
    - scipy >=1.5
    - scikit-learn >=0.23
    - matplotlib-base >=3.5
    - rasterio >=1.3

test:
  source_files:
    - tests
  imports:
    - osmnx
  requires:
    - pip
    - pytest
    - pre-commit
    - hatchling
    - folium
  commands:
    - pip check
    - pytest tests -k "not test_elevation"

about:
  home: https://osmnx.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap.
  description: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap. You can download and model walking, driving, or biking networks with a single line of code then analyze and visualize them. You can just as easily work with urban amenities/points of interest, building footprints, transit stops, elevation data, street orientations, speed/travel time, and routing.
  doc_url: https://osmnx.readthedocs.io
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - gboeing
    - ocefpaf
