{% set name = "osmnx" %}
{% set version = "0.5.4" %}
{% set sha256 = "7d974d5e70759e394c53f275d03a282e55c5b32f814b6571163a4884a7655881" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests
    - numpy
    - pandas
    - geopandas
    - networkx <2.0
    - matplotlib
    - shapely
    - descartes
    - geopy
    - rtree
    - folium

test:
  imports:
    - osmnx

about:
  home: https://github.com/gboeing/osmnx
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Retrieve, construct, analyze, and visualize street networks from OpenStreetMap'
  description: |
    OSMnx is a Python 2 and 3 package that lets you download spatial geometries and
    construct, project, visualize, and analyze street networks from OpenStreetMap's
    APIs. You can download and construct walkable, drivable, or bikable urban networks
    with a single line of Python code, and then easily analyze and visualize them.
  doc_url: https://osmnx.readthedocs.io/en/stable/
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - ocefpaf
    - gboeing
