{% set name = "osmnx" %}
{% set version = "0.4" %}
{% set md5 = "41bb17632a8fae409d202eb12117f83b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests
    - numpy
    - pandas >=0.19
    - geopandas >=0.2.1
    - networkx
    - matplotlib >=2.0
    - shapely
    - descartes
    - geopy
    - rtree >=0.8.3
    - folium

test:
  imports:
    - osmnx

about:
  home: https://github.com/gboeing/osmnx
  license: MIT
  license_file: LICENSE.txt
  summary: 'Retrieve, construct, analyze, and visualize street networks from OpenStreetMap'
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
    - gboeing
