travis:
  secure:
    BINSTAR_TOKEN: eVBZWL0h2FZF1U9bz2tV3aPRfsy/3eTxEoXUy0KPSE/k/o/7a51JJkdlnBRQpSZ7+eSKjOgYKhfE4XkzasX6ZgUsH+HJJa4u1y0sUiDSMiqGyhvLdx0tKmXEu7NmsfAQRG0v95GeoPalRVHHuOuG1gzQL4uQLa1P7Db2RrSZllQlLCrrrVQxSe1vHSl72gCnfzhc/QmF1MBhrrztLPe8gUThul0lA8JryJRaJgCKGu5C3OH7C5HAEyJamuSbWYhbGk68Jfe60Ms4AwjiLxMqJjtujHuaYSczlAC5fUOMqkKKb/MzrZGAR/gKvYqOGtN3lvd43Tj+xw1xFesyhaosMvonMBVJtLl1v1Y9FD47EG23YteZHBLBgy9Rr7PlL8k7sQF4K9BcCmyr09yoSRu81N4ao8YimBH8p9TkQYHefsLfpbhVFNRCu2kubAkWZFsYPaLZoDu/DOb6834whGGrHfuQiiWD4nfLsLP0m79it8oQIwc97yoPR975SCwqIfj/DRoKIQpnBAqgvYLGbCBZ/ZLJJfRcVUKfnLutBZyunfGwgHqAlM1u2UU59qBvvbE93j6dEx6ZGn1dhDXluUbAsUFfswQ3rFT+Kxd58A5sbP66nka4QIUe84EBNND6Qlgl6VMXkcP+1hzTQm2XMW0v5eRB6wJb6JdY8pHnkwnT0Pg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
