travis:
  secure:
    BINSTAR_TOKEN: H7ngvfBi+roCElJ0KidBbFcn4sYHuEnBIhxjD7grN33jgwAjX0ap5QMTxhGi/fzssBy4k50ltAQsJDTs0Szk+GNCvZwuSdDx4dnsmr4hAbTko/vV+wf5gZSYMGdIM4jQyI/ojZ/IxXtAW4RPFCA6r+qMk4TRHmZ8oXZuZiqOcKxAmLxRU+ae+/MJJBIAvY5kgBwI9DAEr71uN8ZtgxXrsgqqcqESTG97rwNVF53VcXvtt9G09RLAfKo0sMRoE6Qu9LY+6FGYZ+/Z8RM5J+C6LVmYQd2HufW8vsHhgcvqBIJDH7L+mvx9x7NvqT2IjTeB7CrGU776HxanPbGuy86Vfu6/cibR8jPipuviAfVJ/rHvtCDbV9+jpicBPdu7gfjDn7cQMDF+be1DJiQGedkvc+UxwnvvUdK+J0LdNpTc8oEmyVQNHN6LUpa7XR5deYGYS3z/Jv6Lk0vkBi7v6PZHDUWuWRnZi6JMane7tbxM8ig3H36MIsneDxcdydhRncO0FWx9pTwUNwY/tOc7EpIg4NzRHJ4Pb+7vPVCi/G+PMhbljfJ8FXuUQSo3TE7gtagb4J6zEw0ZH1X0I6tahkiol5pijkDIGDwfGag+Ka9sJvH3wWqTdVYCXh5s34Lu1ogW2FZEclzl5OfSxRq/g8JnVttpDBcGcIRYpR3LesFkQSk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
