travis:
  secure:
    BINSTAR_TOKEN: pA7Eso52tjf4iH5pU24mMOcUXMeXpiPU9NDIX5hE6wYVGJ7QUeOuHoE8PV+ZRS2GMhuyM/+hMrdTVmsPJvninppXcixsZ/8wQz5O1UQHPX/RyAl6D+CyqxClwJNchMhwRKiK9OfbZGd6OuYydxjpRHYoSEQJ4KR6SKH0FowH0YaUVp8iKBNSaiDgnNKuf9ZCoItUz/orH+0HhG4mvObQS7n/qBTCWGtdouX993aPMoQGUI4CvXfmCsxA+XwUZepVQb3G1u5G8j8HuiX3GB1maSLhUMEJwYRmaeg4ligLPajX0sgVtb1y0Ek8NpgD+/Dqn4n8kZZrDF0w+4ZyvxTRet1MAds/h764rG3isLwHATO9uqygmV72KUi8Fuo253Jtv5IPFkCvX1j9Eg9HcL7bSLePLK0OKQ2PwEBqe/wiZchujI+o88ItN4VHuqE5c+/afrQLriOjJGYVjQDQ2D5mBhAW3ny1hczKpHM75r2tF8fu+nGRsJOtK7rlBpnteBq1kqTgg3Exh65h/OR3eRA8ISFIIrPyLzT/5pE2MXiMz7uofLOGbSExXj771KKIqwABDvNZOp6ALIhFGdDvKjK3NxkbUg8Ur+pCqEml9kNvMMqiyvWb57pLhpxE/Z7Zc5JjNIoh7TesuGLyJBJueQQTYXYSPtOkAnW0LiSDIgPdNmo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
